### PR TITLE
Use Docker official Apache Zookeeper image for OpenShift instead of Debezium version

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

See https://github.com/quarkus-qe/quarkus-test-suite/pull/1431#issuecomment-1741805959, I'm not sure about versioning at all, but I gave up searching for it after 15 mins. Can't see any compatibility matrix, IIRC some version of Zookeeper used to be shipped with Strimzi and now something. Let's verify it experimentally.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Failures definitely related, I don't have time for it, so make this draft.

**Comment by rsvoboda** [comment]
@michalvavrik any plans around this? This looks like important one for other platforms

**Comment by michalvavrik** [comment]
> @michalvavrik any plans around this? This looks like important one for other platforms

Agreed, this should be done. I'll add it to my list on this week.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
it's interesting, because I run OCP tests locally and they passed; difference must be that I run it with released version, I'll check why it doesn't work with a snapshot later

**Comment by michalvavrik** [comment]
I tried to adapt https://quarkus.io/version/main/guides/kafka-reactive-getting-started Docker file to OCP but so far completely filed, all relevant examples in docs and GH are for operator https://strimzi.io/documentation/ https://github.com/strimzi/strimzi-kafka-operator/tree/0.38.0/examples https://github.com/strimzi/ https://strimzi.io/quickstarts/

I'll keep trying, but so far I don't know how to work around `Error syncing load balancer: failed to ensure load balancer: error creating LB floatingip: Resource not found: [POST https://reducted:reducted/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalGatewayForFloatingIPNotFound", "message": "External network 0ac88691-d42e-4b85-8195-1b1206b30318 is not reachable from subnet 74877b27-8eb5-47e6-917e-0dc8dd5ffe49.  Therefore, cannot associate Port 26eb6d1a-87c1-467d-a056-aec5bd96337b with a Floating IP.", "detail": ""}}: {"NeutronError": {"type": "ExternalGatewayForFloatingIPNotFound", "message": "External network 0ac88691-d42e-4b85-8195-1b1206b30318 is not reachable from subnet 74877b27-8eb5-47e6-917e-0dc8dd5ffe49.  Therefore, cannot associate Port 26eb6d1a-87c1-467d-a056-aec5bd96337b with a Floating IP.", "detail": ""}}`. So it's unlikely I'll succeed soon.

**Comment by rsvoboda** [comment]
Please talk to @ozangunalp. Kafka docs seem to be outdated, see for example https://github.com/quarkusio/quarkus/issues/37687 and https://github.com/quarkusio/quarkus/issues/37685

**Comment by michalvavrik** [comment]
> Please talk to @ozangunalp. Kafka docs seem to be outdated, see for example [quarkusio/quarkus#37687](https://github.com/quarkusio/quarkus/issues/37687) and [quarkusio/quarkus#37685](https://github.com/quarkusio/quarkus/issues/37685)

I'll do it in 2024.

**Comment by michalvavrik** [comment]
Apache Kafka 3.6.1 is out and ZooKeeper mode has been deprecated in 3.5. There is a production ready migration from ZooKeeper to KRaft and the Zookeeper mode will be removed in Apache Kafka 4.0 (which is happening in 2024). Might be good idea to explore KRaft instead.

**Comment by michalvavrik** [comment]
I had fun with Kafka in last days so I read a lot of its doc and I am definitely sure Zookeeper must go, so I'm closing this PR.

**Pull request closed without merging**
