### PR TITLE
Fix daily by using isolated deployments

### PR DESCRIPTION
**Pull request by Sgitario**

### CODE REVIEW

**Comment by Sgitario** [comment]
Adding @rsvoboda as @mjurc will be on PTO for two days.
This PR is needed before releasing.

**Comment by Sgitario** [comment]
rerun tests

**Comment by Sgitario** [comment]
Updated by removing workaround for https://github.com/quarkusio/quarkus/issues/18795 that has been fixed in upstream.

**Comment by Sgitario** [comment]
rerun tests

**Comment by Sgitario** [comment]
@rsvoboda the failures in the Native job are caused by:
```
[ERROR] Failed to execute goal on project examples-keycloak: Could not resolve dependencies for project io.quarkus.qe:examples-keycloak:jar:0.0.3-SNAPSHOT: The following artifacts could not be resolved: io.quarkus.qe:quarkus-test-containers:jar:0.0.3-SNAPSHOT, io.quarkus.qe:quarkus-test-openshift:jar:0.0.3-SNAPSHOT, io.quarkus.qe:quarkus-test-kubernetes:jar:0.0.3-SNAPSHOT, io.quarkus.qe:quarkus-test-service-keycloak:jar:0.0.3-SNAPSHOT: Could not find artifact io.quarkus.qe:quarkus-test-containers:jar:0.0.3-SNAPSHOT in libs-snapshot-local-mirror (http://10.0.139.54:8040/artifactory/libs-snapshot-local) -> [Help 1]
```

However, for JVM, it worked fine. My guess is that the dependencies in the local repository are evicted or for some reason are not reachable: I would need to dig further into these issues (they worked fine locally).

Spite the above, I think we should proceed with this PR and is blocking us to release 0.0.3 which is needed for our test suites.

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
