### PR TITLE
Fix and extend release version checker

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Fixes problems with globbing and adds additional check of next-version in `project.yml` 

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
@michalvavrik do you want from me some examples of new added checks?

**Comment by gtroitsk** [comment]
@michalvavrik I made some examples

Main scenario: `project.yml` next-version must follow current-version

**Latest pre-release 1.6.0.Beta1**
[main] success 
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995462717

[main] failure
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995472851/job/27627684518

**Latest released 1.5.1 (has “latest” tag)**
**[1.5.z as latest LTS]**
Success   https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995636331/job/27628237024

Failure  
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995646444/job/27628269444

Beta tag failure
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995659518/job/27628309994

**Latest release 1.6.0
Latest published 1.5.1 (no tag)
[1.5.z as oldest LTS (1.3.z)]**
Success 
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995743522/job/27628587111

Failure  
https://github.com/gtroitsk/quarkus-test-framework/actions/runs/9995757571/job/27628631130

**Comment by gtroitsk** [comment]
Plan for `1.3.z` branch during backports
It requires to release 1.3.0, so probably change https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/v1.3.0.Beta31

After, the latest version should be 1.3.1 as a blank release or changed https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/1.3.1.Final

What strategy do you prefer?

**Comment by michalvavrik** [comment]
Let's go with the easiest way, if we need 1.3.0 to have this check passing, it's better to do extra release than to invest more time into this task.

**Review by michalvavrik — APPROVED** [review]

**Pull request merged**
