### PR TITLE
Refactor Kubernetes Client

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Drop reflection and usage of deprecated classes and methods as we are already using Quarkus 2.15 that uses Kubernetes client 6.2.0, optimize namespace detection and do not keep unnecessary master client variable.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Tests fail over insufficient memory during native build, I'll try to re-run them.

**Review by jsmrcka — APPROVED** [review]
Looks good. Thanks.

The native CI failure is most likely unrelated and I wasn't able to reproduce it.

**Comment by jsmrcka** [comment]
Related to https://github.com/quarkus-qe/quarkus-test-framework/pull/588.

**Pull request merged**
