### PR TITLE
Make OCP config map name unique for same mount paths

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

fixes:

- config map name is not unique when more than one file is mounted to same directory
- `/etc/|server-keystore.jks` was mounted to `/etc//server-keystore.jks`, now it is `/etc/server-keystore.jks`

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by jedla97 — CHANGES_REQUESTED** [review]
Thanks for this PR! It§s look good just one thing. Can you use `joinMountPathAndFileName` also here https://github.com/quarkus-qe/quarkus-test-framework/pull/992/files#diff-8a361a4b7ddbed5806dc8db9f66279da5238c3d66406b50ed40aa90a8b708d74L858

**Comment by michalvavrik** [comment]
> Thanks for this PR! It§s look good just one thing. Can you use `joinMountPathAndFileName` also here https://github.com/quarkus-qe/quarkus-test-framework/pull/992/files#diff-8a361a4b7ddbed5806dc8db9f66279da5238c3d66406b50ed40aa90a8b708d74L858

done

**Comment by michalvavrik** [comment]
> Thanks for update! LGTM!

Thank you, I'll just wait for `validate format` step to pass as I don't want to wait for whole CI again. I have other PR on the way changing related code, you will see CI there today.

**Comment by jedla97** [comment]
> Thank you, I'll just wait for validate format step to pass as I don't want to wait for whole CI again. I have other PR on the way changing related code, you will see CI there today.

Np as it pass last time I don't think this change cause any problem. So I'm ok with it

**Pull request merged**
