### PR TITLE
Support encrypted communication between Quarkus app with MSSQL JDBC extension and SQL Server

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Adds support for encrypted communication between Quarkus app with JDBC MSSQL extension and SQL Server because Microsoft documentation says in FIPS-enabled environment you should do that: https://learn.microsoft.com/en-us/sql/connect/jdbc/fips-mode?view=sql-server-ver16#appropriate-configuration-parameters

Despite the docs above, it doesn't seem to be required with Red Hat OpenJDK 21 (works both with TLS and without TLS) and never works in FIPS-enabled environment with Red Hat OpenJDK 17.

So my plan in regards of FIPS:

- disable MSSQL tests on OpenJDK 17 in FIPS-enabled environment
- open upstream issue at the very least to have this non-working configuration tracked somewhere
- run at least one of tests with TLS because:
  - that's what official documentation imply is way to go
  - I have no idea why the behavior is different with 21, so having TLS backup seems like a good idea
  - SQL Server driver by default runs everything even in non-FIPS env via encrypted communication channel, only reason it worked for us till now is that we explicitly disable it everywhere, for example here: https://github.com/quarkus-qe/quarkus-test-suite/blob/64932fda5970db8e29081e168337d010ee504f84/sql-db/sql-app/src/test/resources/mssql.properties#L5

This is how I tested it (FIPS/no FIPS): https://github.com/quarkus-qe/quarkus-test-suite/compare/main...michalvavrik:quarkus-test-suite:feature/sql-server-fips

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
The `OpenShiftDockerBuildIT` failed in OpenShift Tests in JVM over network communication with OpenShift. I am not going to rerun it as it has no relation to changes here.

**Review by mjurc — APPROVED** [review]
LGTM

**Pull request merged**
