### PR TITLE
Release 1.4.2.Beta9

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Release contains:
- #1059
- #1064
- #1063
- #1067
- #1065
- #1066
- #1061
- #1060
- #1056
- #1058
- #1055
- #1057
- #1051
- #1050
- #1049
- #1047
- #1046
- #1045
- #1072
- #1073
- #1071
- #1074
- #1070 

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Release
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run tests

**Review by michalvavrik — CHANGES_REQUESTED** [review]
I need to get a PR in and make a release, so we might as well do it together. Please wait till the end of the day I'll try to create fix ASAP. Thx

**Comment by michalvavrik** [comment]
@gtroitsk this one is needed #1070 and #1074 is what I'd like to get in before the FW is released.

**Comment by gtroitsk** [comment]
run tests

**Comment by michalvavrik** [comment]
@gtroitsk can you analyse OCP failures, please?

**Comment by gtroitsk** [comment]
> @gtroitsk can you analyse OCP failures, please?

Yes, I will

**Comment by gtroitsk** [comment]
@michalvavrik Failures in management module in OC JVM are weird, I need more time to investigate them properly. In Native `OpenShiftGreetingResourceIT` we need to make service renaming. `OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT` also need more time to investigate. 
These 2 mentioned tests also fails in daily Jenkins runs for some time

**Comment by gtroitsk** [comment]
I had mentioned that we still have next warning`oc: Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+`. I think that we must be completely migrated to "Deployments"

**Review by michalvavrik — APPROVED** [review]
LGTM, let's  be careful with merging this into TS. We will need OCP tests.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
I rerun and analyzed failures, I think most of them goes down to the quay.io network issues.

**Comment by michalvavrik** [comment]
My conclusion is there are failures in the examples that we need to fix, but I'm not yet aware of failure that is problem with this release, so I suggest to merge this and run OCP TS before bumping version in FW.

**Pull request merged**
