### PR TITLE
[1.5.z] Backport TLS registry support

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Bumps:
- Quarkus from 3.14.0 to 3.14.2 so that we run tests present in backports that test this PR https://github.com/quarkusio/quarkus/issues/42752

Backports:

- https://github.com/quarkus-qe/quarkus-test-framework/pull/1281
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1280
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1272
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1277
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1276
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1270
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1268
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1267

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Backports
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
`PR / Linux - JVM build - Latest Version (999-SNAPSHOT, 17) (pull_request) ` failure in Quarkus CLI module is consequence of the https://github.com/quarkusio/quarkus/pull/43005. It also happens on the main branch https://github.com/quarkus-qe/quarkus-test-framework/pull/1286 therefore it is unrelated.

Basically, the issue is that we don't run 1.5.z against 3.14 SNAPSHOT, but we use 999-SNAPSHOT.

**Comment by michalvavrik** [comment]
run tests

**Review by jedla97 — APPROVED** [review]
Thanks for backport! Commits matching, contains cherry pick message, so from my side LGTM!

Also need to check what new things this amazing effort offer.

**Comment by michalvavrik** [comment]
Thanks. Both OpenShift runs are green, merging.

**Pull request merged**
