### PR TITLE
Use supported GH action for JDK installation

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
@fedinskiy why not v3? https://github.com/marketplace/actions/setup-java-jdk

**Comment by fedinskiy** [comment]
@michalvavrik to have the same version in FW and TS

**Comment by michalvavrik** [comment]
Or your opinion, it's no super important...

**Comment by rsvoboda** [comment]
Upstream uses `actions/setup-java@v3` - https://github.com/quarkusio/quarkus/blob/main/.github/workflows/ci-actions-incremental.yml#L131

My vote is on v3.

**Review by michalvavrik — APPROVED** [review]
LGTM, thanks for changes

**Comment by fedinskiy** [comment]
@michalvavrik well, according to their changelogs, there were some differences in caching, underlying nodejs version and in support for Microsoft JDK. I do not consider these features to be that important enough. On the other side, changing the version of the action should not break anything either, so it is just a question of one more PR :)

Since Rostislav also vote for v3, then I yield. There is a PR for TS: https://github.com/quarkus-qe/quarkus-test-suite/pull/850

**Pull request merged**
