### PR TITLE
Release 1.6.0.Beta2

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Release contains: 

- #1277
- #1276
- #1274
- #1272
- #1270
- #1269
- #1268
- #1267
- #1266
- #1263
- #1264

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Regarding OpenShift native failures: I just run OCP CI here https://github.com/quarkus-qe/quarkus-test-framework/pull/1277, it is same HEAD + release commit. There failed different test, therefore it's flaky and not related.

**Comment by fedinskiy** [comment]
@michalvavrik please create a task in Jira to investigate the failure

**Review by fedinskiy — APPROVED** [review]

**Comment by michalvavrik** [comment]
> @michalvavrik please create a task in Jira to investigate the failure

makes sense @fedinskiy , done https://issues.redhat.com/browse/QQE-951

**Pull request merged**
