### PR TITLE
Release 1.3.0.Beta10

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
LGTM

**Comment by michalvavrik** [comment]
Let's summarize PRs contained in this release @fedinskiy :-)

**Comment by fedinskiy** [comment]
@michalvavrik we have release drafts to do that for us, no?

**Comment by michalvavrik** [comment]
Okay, let see if it works. I always did it manually, thanks.

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
CI failure on the latest is due to https://github.com/quarkusio/quarkus/issues/32219

**Pull request merged**
