### PR TITLE
bugfixes on docker shared network and support quarkus.args

### PR DESCRIPTION
**Pull request by pjgg**
### Summary

* Support docker containers shared network
* Support `quarkus.args` on Quarkus prod applications
* Add a docker shared network example ([Temporal](https://temporal.io/) orchestration engine example)
* Add a quarkus prod with args example ([picocli](https://quarkus.io/guides/picocli))
* Fix an issue in the main pom related to `javax -> jakarta` migration

Please check the relevant options

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### Checklist:
- [X] Example scenarios has been updated / added
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
This PR delivers quite a few changes in different areas. There should be dedicated PR per area!

What's the motivation to introduce quarkus.args support?

What's the motivation to introduce shared network for  containers?

**Comment by pjgg** [comment]
1. `What's the motivation to introduce 'quarkus.args' support?` 

There are several scenarios where `quarkus.args` should be supported. For example, all command cli Quarkus application requires this argument. 

This commit allow you to create your quarkus test app by this way:

```
static final String NAME = "Pablo";

  @QuarkusApplication
    static final RestService app = new RestService()
            .withProperty("quarkus.args", "helloWorld -n " + NAME);
```

Currently, this is not supported and your best approach is to do something like this:
```
@RegisterExtension
    static final QuarkusProdModeTest helloWorld = new QuarkusTemporalAppBuilder(helloWorldServer)
            .withApplicationRoot((jar) -> jar.addClasses(Utils.findAllClassesFromSource()))
            .setApplicationName("helloWorld")
            .setApplicationVersion("0.1-SNAPSHOT")
            .setCommandLineParameters("helloWorld", "-n " + NAME)
            .setExpectExit(true).setRun(false);
```

This approach is not integrated with Quarkus test framework so don´t expect to use the default RestAssurance client and other features. You have to do everything by your self. 

2. `What's the motivation to introduce shared network for containers?`

If you have a complex scenario with several containers and each container depends on another container you should run all containers into the same network, otherwise, you will get a connection refused error (because there is no visibility between containers). Currently, we have several scenarios as this one, for example with Kafka (Kafka + ZK + Registry), but are hidden by internal Quarkus test framework components as `KafkaContainer`

For example

```
  @KafkaContainer(vendor = KafkaVendor.STRIMZI, withRegistry = true, registryPath = "/apis/registry/v2")
    static final KafkaService kafka = new KafkaService();
```

This commit allows you to create complex scenarios with the current `container` annotation

For example

```
 @Container(image = "docker.io/library/postgres:latest", port = POSTGRESQL_PORT, expectedLog = "listening on IPv4 address", networkAlias = TEMPORAL_DB_TYPE, networkId = TEMPORAL_DB_TYPE)
    static PostgresqlService postgres = new PostgresqlService()
            .with(POSTGRES_USER, POSTGRES_PWD, "temporal");

    @Container(image = "temporalio/auto-setup:1.19.0", port = TEMPORAL_PORT, expectedLog = "Temporal server started", networkId = TEMPORAL_DB_TYPE)
    static DefaultService temporal = new DefaultService()
            .withProperty("POSTGRES_USER", () -> postgres.getUser())
            .withProperty("POSTGRES_PWD", () -> postgres.getPassword())
            .withProperty("DB", TEMPORAL_DB_TYPE)
            .withProperty("DB_PORT", "" + POSTGRESQL_PORT)
            .withProperty("POSTGRES_SEEDS", TEMPORAL_DB_TYPE)
            .withProperty("DYNAMIC_CONFIG_FILE_PATH", DEFAULT_POSTGRES_CONFIG)
            .withProperty("DEFAULT_NAMESPACE", NAMESPACE)
            .withProperty("DEPLOYMENT_CASS",
                    String.format("%s::%s|%s", CONTAINER_RESOURCE, CONTAINER_FILE_DEPLOYMENT_PATH, DEPLOYMENT_CASS_FILE))
            .withProperty("DOCKER_YAML",
                    String.format("%s::%s|%s", CONTAINER_RESOURCE, CONTAINER_FILE_DEPLOYMENT_PATH, DOCKER_FILE))
            .withProperty("DEPLOYMENT_SQL",
                    String.format("%s::%s|%s", CONTAINER_RESOURCE, CONTAINER_FILE_DEPLOYMENT_PATH, DEPLOYMENT_SQL_FILE))
            .onPostStart(service -> wait(Duration.ofSeconds(10)));
```

In this example, you can see that both containers share a Network called "TEMPORAL_DB_TYPE"

**Comment by rsvoboda** [comment]
PR needs to be split into 3 PRs, one for fixes, one for args, and one for the shared network.

Details provided in the comment abo need to be present in the description of the appropriate PR so the reviewer and people looking into the PR after some time get the context quickly.
Please do not forget to enhance the documentation - https://github.com/quarkus-qe/quarkus-test-framework/wiki

**Review by michalvavrik — CHANGES_REQUESTED** [review]
Hey @pjgg ,

I'm really looking forward for the review, this looks very interesting, thank you. The request to divide this PR into 3 seems reasonable to me, please copy there explanation you provided in the comment below and it will be just fine.

Thank you!

**Pull request closed without merging**
