### PR TITLE
[resolves #378] Support rest of OpenShift deployments with GitRepository

### LINKED ISSUE #378: Openshift deployment strategy is not applied when used together with @GitRepositoryQuarkusApplication
When using `@QuarkusScenario` + `@GitRepositoryQuarkusApplication` the behaviour is that the source code is cloned and maven package the app and run tests against it.

I would expect the similar behaviour with `@OpenShiftScenario(deployment = OpenShiftDeploymentStrategy.UsingOpenShiftExtension)` + `@GitRepositoryQuarkusApplication` so it would clone the source code {{app}}, maven would execute openshift install on top of {{app}} and then executes tests against it. Right now it doesn't respect the type of deployment and forces to use S2I.

Following line can be observed when above combination is used (which seems wrong to me).
```
11:19:59,788 INFO  Running command: oc apply -f /Users/llowinge/Redhat/quarkus/camel-q-test-suite/quickstarts/file-ftp-bindy/target/OpenShiftFileFtpBindyQuickstartIT/app/openshift.yml -n ts-cmfxcxjptw
```

### PR DESCRIPTION
**Pull request by llowinge**
Covers following new combinations of `@GitRepositoryQuarkusApplication` with:

- `@OpenShiftScenario(deployment = OpenShiftDeploymentStrategy.UsingContainerRegistry)` 
- `@OpenShiftScenario(deployment = OpenShiftDeploymentStrategy.UsingOpenShiftExtension)`
- `@OpenShiftScenario(deployment = OpenShiftDeploymentStrategy.UsingOpenShiftExtensionAndDockerBuildStrategy)`

and `@OpenShiftScenario(deployment = OpenShiftDeploymentStrategy.Build)` remains the same (acts as S2I).

If it will be OK with you, i will prepare documentation to WiKi.

### CODE REVIEW

**Comment by llowinge** [comment]
@mjurc @pjgg FYI

**Comment by mjurc** [comment]
@llowinge Hey, thanks for MR! Before I check the code, may I ask you to update the applications in `examples/external-applications` with the new feature you've add?

**Comment by llowinge** [comment]
I've tried to apply `UsingOpenShiftExtension` deployment, but it doesn't work as the https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started doesn't contain `quarkus-openshift` extension. Could you recommend me which git app i should use to cover that scenario ?

**Comment by mjurc** [comment]
@llowinge I'm not sure if we even have any such app anywhere, actually.

Thinking about it, it kind of limits the usability of this deployment strategy, maybe?

**Comment by llowinge** [comment]
@mjurc We have the `quarkus-openshift` in our quickstarts. So the usability is there. The question is if the deployment strategy should eg. add the extension to the pom.xml if not found ?

**Comment by mjurc** [comment]
@llowinge I'm fine with how it is as of now, and you can add the example application you've mentioned.

If the usecase needs to be expanded by adding the extension into the appication from repo, we can consider it later. Or do you need it right now?

**Comment by llowinge** [comment]
@mjurc I don't need it now, it was meant more for better usability for you. Ok, i will use the camel-quarkus example and should i place it under `examples/external-applications` ?

**Comment by mjurc** [comment]
@llowinge Sounds good to me!

**Review by mjurc — APPROVED** [review]
Looks good to me - thanks for the pull request!

**Comment by llowinge** [comment]
@mjurc I've updated documentation in https://github.com/llowinge/quarkus-test-framework/wiki/6.-Openshift/fbc15321e1123c3ac15651db63544e8f1e9b62b9

**Comment by rsvoboda** [comment]
@llowinge sent you an invite for the Write role. You should be able to edit Wiki on your own now.
And congrats to the elevated role in this repository!

**Pull request merged**
