### PR TITLE
1.1.0.Beta6 Release

### PR DESCRIPTION
**Pull request by pjgg**
### Summary

1.1.0.Beta6 release

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
I thin k releases need to be created from branch in this repo - e.g. direct edit of the file using GitHub UI.

I don't think it should be done from the fork because of credentials propagation if I recall correctly. cc @mjurc

**Comment by rsvoboda** [comment]
see for example https://github.com/quarkus-qe/quarkus-test-framework/pull/424

**Comment by rsvoboda** [comment]
another topic 1.1.0.Beta6 vs, 1.1.0.Final

I would go with 1.1.0.Final

**Comment by pjgg** [comment]
Moved to: https://github.com/quarkus-qe/quarkus-test-framework/pull/469

**Pull request closed without merging**
