### PR TITLE
Enable Camel example external applications

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

https://github.com/apache/camel-quarkus-examples.git is now on Quarkus 3.y, so we should be fine re-enabling them.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Review by jedla97 — APPROVED** [review]
Thanks for enabling these! LGTM!
For openshift error, by go trough them, I see there is no problem caused by PR (all seems as intermittent).

**Pull request merged**
