### PR TITLE
Do not use deprecated classes and methods

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Removes a single deprecated class and updates usage of deprecated functionality, which was completely removed earlier

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — DISMISSED** [review]
According to https://github.com/testcontainers/testcontainers-java/pull/9139/files this should work with `confluentinc/cp-kafka` images version `7.4.0` and later and we are on the 7.6.1 version. So LGTM if CI agrees.

**Comment by michalvavrik** [comment]
Looks like you will need a rebase.

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
After an update to the class for running Kafka, testcontainers are not able to connect to cp-schema-registry container. This library is really a gift, that keeps on giving.

@michalvavrik  I would not be able to work on this PR during the next week, so feel free to close it and the related task

**Comment by mjurc** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
Change in the port seems expected https://docs.confluent.io/platform/current/installation/migrate-zk-kraft.html#step-2-configure-a-kraft-controller-quorum and the new dependency should allow nicer checks, good idea. Thank you

**Comment by fedinskiy** [comment]
@michalvavrik the only failure in ci is native OCP with "ImagePullBackOff" and age 1. Do you want to rerun it or is it fine?

**Comment by michalvavrik** [comment]
> @michalvavrik the only failure in ci is native OCP with "ImagePullBackOff" and age 1. Do you want to rerun it or is it fine?

OpenShiftS2iQuickstartUsingDefaultsIT is notoriously flaky.

**Comment by michalvavrik** [comment]
or better, it is also failing in periodic jobs, so I'll check why

**Pull request merged**
