### PR TITLE
Bump strimzi kafka testcontainer to 0.107.0

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Fixing #1186

This is the draft to check if the new strimzi fix work. Will change this after they release full version.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
Run CI 3 times and kafka error not appear any time so it should be fixed. Now waiting for 0.107.0 release which should be at the start of the next week

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
Openshift native failure is not related to this bump

**Comment by jedla97** [comment]
Maybe this should be also backported?

**Comment by rsvoboda** [comment]
I don't think we have Kafka with KRaft in 3.8 branch. @fedinskiy can you confirm please?

**Comment by fedinskiy** [comment]
@rsvoboda we have Kafka with Kraft in all 3.x branches.

@jedla97 could you create backport PRs as well? We also should update the TS to 0.107.0, since the upstream Quarkus brings in an older version

**Review by fedinskiy — APPROVED** [review]

**Comment by gtroitsk** [comment]
I remove backport labels as changes were already backported

**Pull request merged**
