### PR TITLE
Move to ubi-minimal:8.5

### PR DESCRIPTION
**Pull request by rsvoboda**
Move to ubi-minimal:8.5

### CODE REVIEW

**Review by pjgg — APPROVED** [review]
LGTM

**Comment by rsvoboda** [comment]
JVM job rerun ends with 8 failures.
`Failed to push image app into quay.io/quarkusqeteam. Caused by docker failed (executed [docker, push, quay.io/quarkusqeteam/io.quarkus.qe.openshiftusingcontainerregistrypingpongresourceit.app], return code 1)` in 5 out of 8 failed tests. All are "pingpong" related ... cc @mjurc @pjgg 

Don't think those fails are related to my PR

**Comment by mjurc** [comment]
run tests

**Comment by rsvoboda** [comment]
Same failures for native run on ocp 4.6

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by rsvoboda** [comment]
Passed for me, running against ocp 4.6
```
mvn clean install -Pframework
mvn clean install -Pexamples,openshift -Dts.container.registry-url=quay.io/quarkusqeteam -pl examples/external-applications
```

**Comment by rsvoboda** [comment]
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 107.224 s - in io.quarkus.qe.OpenShiftUsingExtensionPingPongResourceIT
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT » KubernetesClient
[ERROR]   OpenShiftUsingExtensionAndServerlessPingPongResourceIT » NoHttpResponse app-ts...
[INFO]
[ERROR] Tests run: 7, Failures: 0, Errors: 2, Skipped: 0
```
When using `main`  and ocp46 cluster

Commands
```
docker login quay.io
mvn clean install -Pframework
mvn clean install -Pexamples,openshift -Dts.container.registry-url=quay.io/quarkusqeteam -pl examples/pingpong
```

**Pull request merged**
