### PR TITLE
Enable test as the issue is closed

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Enable tests which were affected by https://github.com/quarkusio/quarkus/issues/38018

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
Please DO NOT MERGE yet looking into connection with ocp

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
LGTM, thanks for opening the upstream issue.

**Pull request merged**
