### PR TITLE
Release 1.5.0.Beta7

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Release FW to fix TS.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Release
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
release version check seems to be based on the latest published release, I think it needed based on pre-releases as well @gtroitsk . Recently I learned from @mjurc that betas must be prereleases so now the latest one is 1.4.4.

**Review by jedla97 — APPROVED** [review]
LGTM! The commit is OK and  versions are OK.

**Comment by jedla97** [comment]
Looking at fail and shouldn't be latest version 1.4.6 base on https://github.com/quarkus-qe/quarkus-test-framework/tags ?

**Comment by michalvavrik** [comment]
> Looking at fail and shouldn't be latest version 1.4.6 base on https://github.com/quarkus-qe/quarkus-test-framework/tags ?

you are right, I created it manually now (no notes body).

**Pull request merged**
