### PR TITLE
Fix deployment by quarkus-openshift extension

### PR DESCRIPTION
**Pull request by jsmrcka**
### Summary

Result of https://github.com/quarkusio/quarkus/pull/29652. See also related discussion in
https://github.com/quarkusio/quarkus/issues/29921.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Review by mjurc — APPROVED** [review]
LGTM.

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
I have re-done the PR, so that the fix would work for both snapshot and released Quarkus.
The CI failures seem to be unrelated and appear in other PRs / runs. The actual issue with deploying via `quarkus-openshift` extension does not appear in the runs.

This fix has also been tested (locally) in QE TS by executing 15 scenarios from https://github.com/quarkus-qe/quarkus-test-suite/pull/959 using patched TF.

**Review by mjurc — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
