### PR TITLE
Bump Quarkus to 2.15.1.Final

### PR DESCRIPTION
**Pull request by rsvoboda**
Bump Quarkus to 2.15.1.Final

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
Failed test is `io.quarkus.qe.OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT` with 11 fails in a row

**Comment by jsmrcka** [comment]
run tests

**Review by mjurc — APPROVED** [review]
Thanks!

**Pull request merged**
