### PR TITLE
Patch Quarkus Kubernetes Client upgrade to 6.1

### PR DESCRIPTION
**Pull request by jsmrcka**
### Summary

See
- https://github.com/quarkusio/quarkus/pull/27677
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.13#kubernetes-client-upgraded-to-61

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Review by pjgg — APPROVED** [review]
I have run some smoke tests just to double-check OCP integration and looks good
Overall LGTM

**Comment by michalvavrik** [comment]
OC JVM mode failure is not related.

**Comment by pjgg** [comment]
the issue on OCP / CI is not related to this PE

**Pull request merged**
