### PR TITLE
Add condition to run Helm tests

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Some tests need to have Helm/Helmfile installed locally. 
This PR use EnabledIf condition and HelmUtils methods to verify this.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run tests

**Comment by rsvoboda** [comment]
Can be `isHelmInstalled` method implemented just once and placed in helm module inside an util class?

**Comment by rsvoboda** [comment]
https://junit.org/junit5/docs/5.8.0/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/EnabledIf.html#value() say's it's possible

```
The name of a method within the test class or in external classes to use as a condition for the container's execution.

Condition methods must be static if located outside the test class, or if @EnabledIf is used at class level.

Condition methods in external classes must be referenced by fully qualified method name —
  for example, com.example.Conditions#isEncryptionSupported.
```

**Comment by gtroitsk** [comment]
HelmUtils class was implemented to verify existence of Helm/Helmfile.

**Review by michalvavrik — CHANGES_REQUESTED** [review]
Problem with using hardcoded `helm` and `helmfile` command is that they are only default command names, Pablo made this configurable with `ts.quarkus.helmfile.cmd` and `ts.quarkus.helm.cmd`.

You can see how actual value is looked up  `io.quarkus.test.bootstrap.QuarkusHelmClient#COMMAND` & `io.quarkus.test.bootstrap.QuarkusHelmFileClient#COMMAND` and there comes with the moment when `PropertyLookup` can be used. IMHO all that you need to do is to make these static constants package private and use them (because you are going to move `Helm Utils` to the same package anyway).

Please make sure to test this (for example with alias and setting the property), thank you!

**Comment by michalvavrik** [comment]
@gtroitsk failure is in `examples-quarkus-helm`, can you have a look?

**Comment by gtroitsk** [comment]
@michalvavrik Seems like it's an error from https://github.com/quarkiverse/quarkus-helm or Quarkus upstream, I can't reproduce this on my machine with 999-SNAPSHOT

**Comment by michalvavrik** [comment]
> @michalvavrik Seems like it's an error from https://github.com/quarkiverse/quarkus-helm or Quarkus upstream, I can't reproduce this on my machine with 999-SNAPSHOT

@gtroitsk that's not satisfactory conclusion :-) I don't have a time to debug now, so if you are certain you have the latest Helm / upstream and can't to reproduce it, let's keep PR on hold till I find little time. I don't see relation to your actions, but we can't merge it considering this PR is making changes in module that is failing (meaning = we can't test it).

**Comment by michalvavrik** [comment]
@gtroitsk failure is unrelated as it also appears elsewhere https://github.com/quarkus-qe/quarkus-test-framework/pull/819, but let's wait till you finish investigation so that we can test it

**Review by michalvavrik — APPROVED** [review]
Thanks for the fixes.

**Comment by michalvavrik** [comment]
Failure unrelated.

**Pull request merged**
