### PR TITLE
Fix OpenShiftClient failures

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

This PR does 2 things (blimey) in 2 commits (so we could independently revert them):
- There has been ongoing issues when we are selecting `OpenShiftClient` method that we want to invoke. You can reproduce it f.e. with `mvn clean verify -Dit.test=OpenShiftApiServerConfigSecretConfigIT -Dopenshift -Dquarkus.openshift.jar-file-name=quarkus-run.jar -f config/` in Quarkus Test Suite project. I run several tests and the solution you suggested in previous PR was a right way to go. I made mistake not to accept it. Now, method is chosen based on param's class assignability.

- Works around https://github.com/quarkusio/quarkus/issues/28108 by setting JAR file name explicitly. The issue is both in TFW (f.e. `OpenShiftUsingExtensionComputedValuesUsingCustomPropertiesPingPongResourceIT`) and TS whenever `OpenShiftDeploymentStrategy.UsingOpenShiftExtension` is used.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
compilation error `/home/runner/work/quarkus-test-framework/quarkus-test-framework/examples/kafka-registry/src/main/java/io/quarkus/qe/kafka/config/VertxKProducerConfig.java:[5,29] package io.quarkus.arc.config does not exist` looks weird, I'll check it.

**Comment by rsvoboda** [comment]
https://github.com/quarkus-qe/quarkus-test-framework/pull/574 fyi

**Comment by michalvavrik** [comment]
compilation issue is going to be resolved by https://github.com/quarkus-qe/quarkus-test-framework/pull/574

**Comment by michalvavrik** [comment]
thank you

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
I can genuinely see no exceptions in logs for failing OC tests, just  _WARNING [app] Service didn't start in PT5M minutes._ I'll debug it and get back here once I have a solution.

**Comment by michalvavrik** [comment]
Ah, found it.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
I've added a fallback (smth like "if you can't find proper match, close your eyes and think of old good England") and run troublesome tests - passing now. Let's wait for CI.

**Comment by michalvavrik** [comment]
OC failures unrelated:

HELM failures in OC are not related - _Failed to pull image "nginx:1.16.0": rpc error: code = Unknown desc = pinging container registry 10.0.205.208:5000: Get "http://10.0.205.208:5000/v2/": dial tcp 10.0.205.208:5000: connect: connection refused_


OpenShiftGreetingResourceIT failure goes down to _Failed to pull image "docker.io/bitnami/consul:1.13.1": rpc error: code = Unknown desc = pinging container registry 10.0.205.208:5000: Get "http://10.0.205.208:5000/v2/": dial tcp 10.0.205.208:5000: i/o timeout_

OpenShiftBasicInfinispanBookCacheIT, OpenShiftUsingJksInfinispanBookCacheIT go down to _Failed to pull image "docker.io/infinispan/server:13.0": rpc error: code = Unknown desc = pinging container registry 10.0.205.208:5000: Get "http://10.0.205.208:5000/v2/": dial tcp 10.0.205.208:5000: i/o timeout_

OpenShiftMySqlDatabaseIT go down to _Failed to pull image "docker.io/mysql:8.0.30": rpc error: code = Unknown desc = pinging container registry 10.0.205.208:5000: Get "http://10.0.205.208:5000/v2/": dial tcp 10.0.205.208:5000: i/o timeout_

**Pull request merged**
