### PR TITLE
Fixed testing on linux jvm released version in daily.yaml

### PR DESCRIPTION
**Pull request by TimonCzech**
### Summary

Noticed that there were not any tests in daily linux jvm released version so I decided to investigate and fix it

link to the daily test: https://github.com/quarkus-qe/quarkus-test-framework/actions/runs/10782729803/job/29903283110

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by jedla97 — APPROVED** [review]
Thanks for fixing this! LGTM!

Testing run for daily should be [this one](https://github.com/TimonCzech/quarkus-test-framework/actions/runs/10828920679/job/30045356702#step:5:8) which showing the updated CI. Going through log I see that quarkus start with current version.
Log example:
`NFO  [pingpong] 10:27:42,800 examples-pingpong 1.6.0.Beta5-SNAPSHOT on JVM (powered by Quarkus 3.14.2) started in 0.676s. Listening on: http://0.0.0.0:1101/`

**Review by michalvavrik — APPROVED** [review]
Thanks!

**Review by jedla97 — APPROVED** [review]
Thanks for update!

Just note, `EXCLUDE_MODULES` is also not used so it can be removed

**Comment by michalvavrik** [comment]
Let's not waste CI runners, I'll merge this after validation succeeds as CI is not testing anything.

**Pull request merged**
