### PR TITLE
Hash host and port to avoid reading them after shutdown

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Comment by fedinskiy** [comment]
Tests from the TS have passed on a local machine, so I consider this ready for review

**Comment by pjgg** [comment]
@fedinskiy should this changes also go to main branch?

**Comment by pjgg** [comment]
run tests

**Comment by pjgg** [comment]
Errors on OCP are not related to the changes.

**Pull request merged**
