### PR TITLE
[wip] Debug DevModeOracleDevServiceDatabaseIT

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

This PR exists just for debugging. Done this way as I can't reproduce it locally.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
closing as known issue https://github.com/gvenzl/oci-oracle-free/issues/4, let's wait

**Comment by gvenzl** [comment]
Hey @michalvavrik,

The issue has been resolved.

**Comment by michalvavrik** [comment]
thank you @gvenzl

**Comment by gvenzl** [comment]
Of course, please let me know if there are still any other issues.

**Comment by michalvavrik** [comment]
Closing as fixed now.

**Pull request closed without merging**
