### PR TITLE
[1.4] Backport using KRaft mode for Kafka

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

In KRaft mode Zookeper is not used, since brokers communicate to each other directly.
Backports the following PRs:
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1175
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1191

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
Failure looks related, I'll review when the investigation is done. Thanks

**Comment by michalvavrik** [comment]
run tests

**Comment by fedinskiy** [comment]
@michalvavrik to early, I am trying to debug https://github.com/quarkus-qe/quarkus-test-framework/issues/1186 here, so green ci is just accidentally green :)

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Ci failure in jvm build (FromPomXmlStrimziKafkaWithoutRegistryMessagingIT in examples/kafka) is related, but requires for fix in strimiz 0.107.0

**Pull request merged**
