### PR TITLE
Release Beta8 of the framework

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
The title says it all

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Release
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
LGTM

**Comment by michalvavrik** [comment]
looks like `gpg_private_key` is missing as we do use v6 of that GH action and I guess it has been updated in minor

**Comment by mjurc** [comment]
Github actions can only see secrets from the trunk repository. Forks PRs don't have access to secrets.

The releases PRs need to happen from this repository.

**Comment by michalvavrik** [comment]
arg! thanks @mjurc I didn't check

**Comment by michalvavrik** [comment]
> Almost makes me think we should have a check for the origin too for when `.github/project.yml` is changed.

+1

**Comment by mjurc** [comment]
https://github.com/quarkus-qe/quarkus-test-framework/issues/1179

**Pull request merged**
