### PR TITLE
Add check for same repo PR origin for releases

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

closes: #1179 

Release PRs can only be executed if source branch is in same repo, because of GH secrets. This adds a check to verify that it is so. 

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mocenas** [comment]
I've tested this on my own forks:
Passed example: https://github.com/mocenas/quarkus-test-framework/pull/21
Failed example: https://github.com/mocenas/quarkus-test-framework/pull/22

**Review by michalvavrik — APPROVED** [review]
LGTM;

I'd probably call this check differently as 2 release checks are named differently:

```
Check release version / check-release-version (pull_request)
Release check / check-source-repo-is-not-a-fork (pull_request)
```

But it's optional. Feel free to merge it (as this CI is not testing this PR anyway).

**Comment by rsvoboda** [comment]
+1 to sync naming

**Comment by michalvavrik** [comment]
cc @fedinskiy CI failure (wonder if that is flakyness, it seems like daily is ok)

**Comment by fedinskiy** [comment]
@michalvavrik it is flakiness, I saw it during CI for the release, it was cured by rerun. Created https://github.com/quarkus-qe/quarkus-test-framework/issues/1186, will take a look.

**Comment by michalvavrik** [comment]
> +1 to sync naming

I'd not say it's synced. but changed. @rsvoboda merge if you like.

**Comment by rsvoboda** [comment]
I would like to see this
```
Release check / check-release-version (pull_request)
Release check / check-source-repo-is-not-a-fork (pull_request)
```

**Comment by michalvavrik** [comment]
> I would like to see this

TBH me too, but I didn't want to be annoying. It looks better.

**Comment by mocenas** [comment]
I renamed also the version release check, to be consistent.

**Review by michalvavrik — APPROVED** [review]
Thanks

**Pull request merged**
