### PR TITLE
Fix build-time config detection for relocated properties and for config properties from extension deployment modules

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

closes: #1149

the script is based on https://github.com/quarkusio/quarkus/blob/main/docs/src/main/java/io/quarkus/docs/generation/AllConfigGenerator.java

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
` JVM build - Latest Version ` also fails over it in a daily build.

**Comment by rsvoboda** [comment]
How often do we need to have the list updated? Is there any noticeable milestone?

Maybe adding a note into https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md#preconditions for new major/minor releases? 

CC @mjurc

**Comment by rsvoboda** [comment]
Cool, seems it's fine to have this as adhoc action.

> strange how it is most of the build-time and build-time-fixed properties are placed in classes in the runtime modules (for build-time it's waste...)

Worth GH issue?

**Comment by michalvavrik** [comment]
> > strange how it is most of the build-time and build-time-fixed properties are placed in classes in the runtime modules (for build-time it's waste...)
> 
> Worth GH issue?

I run quick check and only found 6 examples of this. However additionally, build-time-runtime-fixed is placed in the runtime so it is auto-detected.


as for opening issue - sadly config classes are treated as part of the API now, which is one of the reasons why there is so long process of migrating config classes to config mapping interfaces (in addition to reflection registration effectiveness), so:

- they won't be ale to move it in case other extension is using it (either quarkiverse or custom)
- they can say it when config phase changes they don't have to change class package (move it)

**Comment by michalvavrik** [comment]
> > JVM build failure goes down to the [quarkusio/quarkus#36826](https://github.com/quarkusio/quarkus/pull/36826)
> 
> What failure? The CI failure?

We have one build failure in the `JVM build - Latest versions` of this PR CI with message `Could not find goal 'native-image-agent' in plugin io.quarkus.platform:quarkus-maven-plugin:3.11.0 among available goals` , my colleague @jedla97 described it in here https://github.com/quarkusio/quarkus/issues/40951.

**Comment by galderz** [comment]
> > > JVM build failure goes down to the [quarkusio/quarkus#36826](https://github.com/quarkusio/quarkus/pull/36826)
> > 
> > 
> > What failure? The CI failure?
> 
> We have one build failure in the `JVM build - Latest versions` of this PR CI with message `Could not find goal 'native-image-agent' in plugin io.quarkus.platform:quarkus-maven-plugin:3.11.0 among available goals` , my colleague @jedla97 described it in here [quarkusio/quarkus#40951](https://github.com/quarkusio/quarkus/issues/40951).

Not a bug

**Review by mjurc — APPROVED** [review]
LGTM - just verifying - the CI failure is caused by wrong Quarkus platform bom version in action?

**Comment by michalvavrik** [comment]
> LGTM - just verifying - the CI failure is caused by wrong Quarkus platform bom version in action?

we need the plugin to use correct version, Jakub tries to address it here https://github.com/quarkus-qe/quarkus-test-framework/pull/1157 (I'll review soon); I wouldn't be worried about this failing as this PR is not specific to Quarkus version and released version was green.

**Pull request merged**
