### PR TITLE
Release 1.3.0.Beta15

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Release 1.3.0.Beta15 contains:

- https://github.com/quarkus-qe/quarkus-test-framework/pull/759
- https://github.com/quarkus-qe/quarkus-test-framework/pull/760
- https://github.com/quarkus-qe/quarkus-test-framework/pull/762
- https://github.com/quarkus-qe/quarkus-test-framework/pull/762
- https://github.com/quarkus-qe/quarkus-test-framework/pull/763
- https://github.com/quarkus-qe/quarkus-test-framework/pull/765

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Release
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Review by fedinskiy — APPROVED** [review]
But lets wait for CI

**Comment by rsvoboda** [comment]
Or .Final will come today with https://github.com/quarkus-qe/quarkus-test-framework/pull/764?

**Comment by michalvavrik** [comment]
> Shouldn't be the release named 1.3.0.Final as Quarkus 3 is final now? cc @mjurc

I have no opinion here. If I had to chose, I'd say final it should be when we finished adjustments necessary for Ghost (so final when Ghost is out) otherwise we will be backporting stuff to 1.3.x

**Comment by mjurc** [comment]
I agree we should wait for Final with Ghost release, so beta is fine imho

**Comment by rsvoboda** [comment]
Ok, let's align towards Ghost, thanks guys!

**Pull request merged**
