### PR TITLE
Release 1.6.0.Beta17

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Main purpose of this is release is to check that our release workflow works with changes made in the https://github.com/quarkus-qe/quarkus-test-framework/pull/1428 so that:

- release will work when we need it
- I can make similar changes in the 1.5.z branch

This release contains:

- https://github.com/quarkus-qe/quarkus-test-framework/pull/1425
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1427
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1428

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by jedla97 — APPROVED** [review]
Looks fine to me, let see if the release works

**Comment by jedla97** [comment]
Release failed when pushing the chages. Believe it's because the jacoco was pushed in meantime looking at git history.

The snapshot is deployed.

btw we probably need this commit manualy pushed

**Comment by michalvavrik** [comment]
> Release failed when pushing the chages. Believe it's because the jacoco was pushed in meantime looking at git history.

argh

> The snapshot is deployed.
> 
> btw we probably need this commit manualy pushed

I'll have a look then, thanks

**Comment by rsvoboda** [comment]
jacoco strikes again :)

**Comment by michalvavrik** [comment]
https://github.com/quarkus-qe/quarkus-test-framework/blob/main/.github/project.yml is up to date now and I created and and RN manually https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/1.6.0.Beta17.

**Comment by michalvavrik** [comment]
No, project.yml is still wrong, must have pushed it wrong. I'll fix it in a gist.

**Pull request merged**
