### PR TITLE
[1.5.z] Backport Fix the Keycloak memory issue on Podman setting JAVA_OPTS_APPEND

### PR DESCRIPTION
**Pull request by jcarranzan**
### Summary

This is a backport contains:
 https://github.com/quarkus-qe/quarkus-test-framework/pull/1389

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by fedinskiy — APPROVED** [review]
Thank you, but please, wait for CI to finish

**Comment by fedinskiy** [comment]
run tests

**Comment by jcarranzan** [comment]
Openshift errors are not related to this MR

**Comment by jedla97** [comment]
@jcarranzan don't forget remove the backport label on the original PR, also for future the commit should contains `(cherry picked from commit X)` by adding -x to cherry pick command.

**Pull request merged**
