### PR TITLE
Disable OpenShift tests, which are broken in Quarkus 3.2.0.Final

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
1. https://github.com/quarkusio/quarkus/issues/34645

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
Hey @fedinskiy that disables tests, no 3.2.0 bump. It is probably not intentional, right? I don't mind though as far as we consider it preparation for 3.2.0 bump. I'm going to change title and desc and merge it.

**Comment by michalvavrik** [comment]
Please create follow-up PR.

**Comment by fedinskiy** [comment]
@michalvavrik that is correct, it looks like 3.2.0 has changes, which broke our format checks.

But I would prefer to run some tests on Openshift before merging this one :)

**Comment by michalvavrik** [comment]
> But I would prefer to run some tests on Openshift before merging this one :)

I didn't run OCP tests because this PR only disables them, I can't imagine how it can break anything. Give me a hint and I shall be smarter next time.

**Pull request merged**
