### PR TITLE
[1.3.z] Update release checker

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Backports  https://github.com/quarkus-qe/quarkus-test-framework/pull/1202 and https://github.com/quarkus-qe/quarkus-test-framework/pull/1209

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
@michalvavrik release check failure is expected as we already have similar release `1.3.1.Final`, script recognized it as `1.3.1`. I don't like to release `1.3.2` as will not contain any changes for RHBQ.

**Comment by michalvavrik** [comment]
> @michalvavrik release check failure is expected as we already have similar release 1.3.1.Final, script recognized it as 1.3.1. I don't like to release 1.3.2 as it will not contain any changes for RHBQ.

Won't this PR trigger the release flow which will fail because you create PR from your fork? TBH I'd prefer to actually make release so that next guy that comes after you can just increment by one. This way, we have this whole compatibility issues behind us.

**Comment by gtroitsk** [comment]
> > @michalvavrik release check failure is expected as we already have similar release 1.3.1.Final, script recognized it as 1.3.1. I don't like to release 1.3.2 as it will not contain any changes for RHBQ.
> 
> Won't this PR trigger the release flow which will fail because you create PR from your fork? TBH I'd prefer to actually make release so that next guy that comes after you can just increment by one. This way, we have this whole compatibility issues behind us.

I create another PR with release after this PR will be merged. So, `1.3.2`  may be the next?

**Comment by michalvavrik** [comment]
> I create another PR with release after this PR will be merged. So, `1.3.2` may be the next?

sounds good

**Review by michalvavrik — APPROVED** [review]
LGTM

**Pull request merged**
