### PR TITLE
Adapt keycloak client to changed URL

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Keycloak container seemingly changed  the URL for authentication. We should adapt our client.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
@fedinskiy I didn't find anything in Quarkus code / PRs or migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6 nor I found anything in Keycloak release notes https://www.keycloak.org/docs/latest/release_notes/index.html. This seems like super breaking change, can you share details?

**Comment by rsvoboda** [comment]
> @fedinskiy I didn't find anything in Quarkus code / PRs or migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6 nor I found anything in Keycloak release notes https://www.keycloak.org/docs/latest/release_notes/index.html. This seems like super breaking change, can you share details? And TS/FW failures?

👍 for this. This needs to be highlighted to the users + more details findout

**Review by michalvavrik — APPROVED** [review]
Yesterday I've mentioned that path used by Keycloak Admin client also doesn't contain  with `/auth/realm` but only `/realm`.

I also found out that `/auth` prefix was deprecated since Quarkus distribution https://keycloak.discourse.group/t/login-page-not-loading/15323 
and you need to use KC_HTTP_RELATIVE_PATH if you want to keep it.

**Comment by michalvavrik** [comment]
It is documented here https://github.com/keycloak/keycloak/blob/8888e3d41c37566bb6d39ddd71d97c1004844a5f/docs/guides/migration/migrating-to-quarkus.adoc#L13. But that also means we won't be able to use legacy Kc with this change.

**Comment by michalvavrik** [comment]
Okay, so I checked and now that we will be able to replace RH SSO https://catalog.redhat.com/software/containers/rh-sso-7/sso7-rhel8-init-container/6160610d5ac6c12504902068?architecture=amd64&image=6526acceccf3f0ae376b179e with RHBK based on Quarkus 3.2 it should be safe to merge this.

**Pull request merged**
