### PR TITLE
Bump Quarkus to 2.13.2.Final

### PR DESCRIPTION
**Pull request by rsvoboda**
Bump Quarkus to 2.13.2.Final

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
Native OCP fails on `io.quarkus.qe.OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT` while JVM one is green.

Kafka related tests seem to be flaky :/

**Comment by rsvoboda** [comment]
SB operator reports Failed status, so there is ENV / Cluster issue

**Comment by michalvavrik** [comment]
I'd suggest Kafka failure is related to `pod/kafka-instance-zookeeper-0                           Back-off restarting failed container`

**Comment by pjgg** [comment]
run tests

**Comment by pjgg** [comment]
Must be some cluster degradation because currently is working as expected. Also, is working on my local environment.

**Review by pjgg — APPROVED** [review]
LGTM

**Pull request merged**
