### PR TITLE
Support FIPS-compatible client certificate generation

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

We use client certificates in TS with insecure algorithms, I'd like to unify its generation and have web client configured with setup based on these generated certs.

You can see that this PR replaces insecure relaxed HTTPS communication with HTTPS communication that verifies host and validates server certificates on client side as well (unlike what Rest Assured did).

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Review by mjurc — APPROVED** [review]
This looks incredibly useful and usable. LGTM.

Do we want this for 1.4 too?

**Comment by michalvavrik** [comment]
> This looks incredibly useful and usable. LGTM.
> 
> Do we want this for 1.4 too?

Yes, and thank you. I've decided to add 2 features now:

- ability to test client unknown to server
- ability to test server unknown to client

The point is it is tested in TS Security/HTTPS module and I want to simplify it. It is very little change (2 flags), so I hope it's okay.

Hence changes. It's also the reason why I cancelled OCP CI (though this PR doesn't really change anything related to OCP, I just wanted to show it's fine).

**Comment by michalvavrik** [comment]
run tests

**Pull request merged**
