### PR TITLE
Fix Kubernetes test scenario 

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Fix issue https://github.com/quarkus-qe/quarkus-test-framework/issues/433

Now services are exposed with NodePort instead of LoadBalancer
`KubectlClient` was updated to use the new functions from Fabric8 Kubernetes client, deprecated functions were removed. 

Existing Kubernetes test coverage was run locally with connection to temporary Kubernetes cluster. 

I add `KubernetesPostgresqlIT`  to test containers creating for basic scenario.

Please check the relevant options

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run kube tests

**Comment by gtroitsk** [comment]
run kube tests

**Comment by michalvavrik** [comment]
I don't really have comments as long as it works (CI is red), because the code looks ok on the first look. I'll re-check when the CI is green, but I don't expect issues. 

Just one question - what will happen if I run K8 tests from 2 different PRs at one time? Is the host always specific to the ephemeral namespace?

**Comment by gtroitsk** [comment]
run kube tests

**Comment by gtroitsk** [comment]
> I don't really have comments as long as it works (CI is red), because the code looks ok on the first look. I'll re-check when the CI is green, but I don't expect issues.
> 
> Just one question - what will happen if I run K8 tests from 2 different PRs at one time? Is the host always specific to the ephemeral namespace?

Host allows to use ephemeral namespace. I don't expect problems running k8s tests in multiple PRs at one time

**Review by michalvavrik — APPROVED** [review]
Good job!

**Pull request merged**
