### PR TITLE
Add CLI feature to update quarkus app

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

We intend to test update of quarkus using CLI tool. Expose the update feature in the framework.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
it's ok for now. Please keep in mind that you will need WAY more and when you will open these follow-up PRs in FW for the update command, we will need tests. At least basic ones. Thank you

**Comment by mocenas** [comment]
> it's ok for now. Please keep in mind that you will need WAY more and when you will open these follow-up PRs in FW for the update command, we will need tests. At least basic ones. Thank you

RN I'm not really sure what will be required in FW, so I created just a basic update method, so we can start writing actual tests in the TS. Quarkus update command doesn't have many more CLI options for update and I'm not sure we will need them at all (but never say never).

Should we actually write tests for this in FW? As I see, quarkus-test-cli module has no tests at all, and those tests would probably duplicate what we (will) have in TS.

**Comment by gtroitsk** [comment]
> > it's ok for now. Please keep in mind that you will need WAY more and when you will open these follow-up PRs in FW for the update command, we will need tests. At least basic ones. Thank you
> 
> RN I'm not really sure what will be required in FW, so I created just a basic update method, so we can start writing actual tests in the TS. Quarkus update command doesn't have many more CLI options for update and I'm not sure we will need them at all (but never say never).
> 
> Should we actually write tests for this in FW? As I see, quarkus-test-cli module has no tests at all, and those tests would probably duplicate what we (will) have in TS.

I think it will be good to have a simple example scenario for quarkus app update in FW. Some tests for CLI are in [QuarkusCliClientIT.java](https://github.com/quarkus-qe/quarkus-test-framework/blob/97f0d1ad7f98c091feb833e7a3b31c0dbad3933c/examples/quarkus-cli/src/test/java/io/quarkus/qe/QuarkusCliClientIT.java).

**Comment by michalvavrik** [comment]
> Should we actually write tests for this in FW?

If you make changes to FW that you cannot verify with FW CI, we cannot know whether changes to FW are correct without running TS which is not automated with FW changes. IMO the FW tests should verify functionality of FW while TS tests should verify Quarkus.

That said, sometimes it is not feasible to test every PR and not all my PRs have tests. I've already approved.

> As I see, quarkus-test-cli module has no tests at all

Here are tests https://github.com/quarkus-qe/quarkus-test-framework/tree/main/examples/quarkus-cli.

> and those tests would probably duplicate what we (will) have in TS.

In TS you will want to verify relevant Quarkus release migrations, here you just want to verify that what your code says it does. It is different because you don't care about specific changes but about specific functionality. I cannot tell you whether there will be duplication because I don't know your test coverage :-) So I don't mind little duplication.

**Comment by michalvavrik** [comment]
> we can start writing actual tests in the TS

What I meant was that this PR is not sufficient to submit tests in the TS and you don't need FW release to start writing tests in the TS with snapshot FW. This PR is completely find, thank you.

**Comment by mocenas** [comment]
I've added a test for update feature. Sorry it didn't dawn on me, that "examples" dir is containing actual tests for the framework.

**Review by michalvavrik — APPROVED** [review]
Thanks for the test.

**Review by gtroitsk — APPROVED** [review]

**Comment by michalvavrik** [comment]
> I've added a test for update feature. Sorry it didn't dawn on me, that "examples" dir is containing actual tests for the framework.

I drop tests from Qurkus CLI module just a month ago https://github.com/quarkus-qe/quarkus-test-framework/pull/1164 :-D So you were not that wrong.

**Pull request merged**
