### PR TITLE
Bump Quarkus to 3.5.0

### PR DESCRIPTION
**Pull request by jsmrcka**
Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jsmrcka** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
Definitely, thanks!

**Comment by michalvavrik** [comment]
Hmm, you marked this as "require OCP run" and I merged it without it. will see soon enough in weekly's, never mind.

**Comment by jsmrcka** [comment]
> Hmm, you marked this as "require OCP run" and I merged it without it. will see soon enough in weekly's, never mind.

I did `run tests`, see above. Everything was green.

**Comment by michalvavrik** [comment]
hmm, but I can see them in this tab

image

looks like a GH bug to me.

**Pull request merged**
