### PR TITLE
Backports for 1.4.z branch to make it feature-full for Quarkus 3.8

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

* Backporting commits labeled by [1.4 backport label](https://github.com/quarkus-qe/quarkus-test-framework/issues?q=label%3Atriage%2Fbackport-1.4%3F+is%3Aclosed).
* Bumping Quarkus to 3.8.4
* Fixing tag in POM SCM config 
* Remove daily action for the branch
* Pin Quarkus version to 3.8 in GH actions
* Pin external applications to 3.8 branches
* Pin CLI tests to 3.8 stream

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
thanks for fixing this

**Pull request merged**
