### PR TITLE
Upgrade keycloak to version 18.0.0

### PR DESCRIPTION
**Pull request by pjgg**
### Summary

Motivation: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.10

 [Keycloak 18.0.0](https://www.keycloak.org/server/importExport) changes (that impact Quarkus test framework): 

- Environment variable `KEYCLOAK_IMPORT` is not supported anymore
- A [new way](https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup) to import a realm at start time was created
- Environment variables `KEYCLOAK_USER` and `KEYCLOAK_PASSWORD` was replaced by `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD`

This PR is trying to integrate all of these required changes into QuarkusTestFramework. 

### PR Design decision 

1. New container annotation was created in order to handle Keycloak scenarios: Currently keycloak component doesn't have its own annotation instead we are using a generic approach, through `@Container` where the developers could set any keycloak version image. The proposal is to use a new annotation called  `KeycloakContainer` where the default values are already set

KeycloakContainer default values:
     - image: `quay.io/keycloak/keycloak:18.0.0`
     - port: `8080`
     - expected started log: `started`
     - `io.quarkus.test.bootstrap.KeycloakService` has new constructors: 

Keycloak 18.0 requires that the imported realms are located into one specific folder: `/opt/keycloak/data/import`
The new KeycloakService has two constructors: 

`public KeycloakService(String realmFile, String realm)` // by default realmDestPath is set to `/opt/keycloak/data/import`
`public KeycloakService(String realm)` // could be useful if you want to setup a keycloak without realm

2. A new way to attach resources to a container has been created: 

Nowadays if you want to attach some file to your container you should add a property with the following value:

```
myContainer.withProperty("KEYCLOAK_IMPORT", "resource::/tmp/myRealm.json")
```

The value "prefix", `resource::` will trigger a  background command in order to create a configMap or to push the above file into the container. However, this "prefix" assume that the file destination path was the same as the original location. Unfortunately on Keycloak this is not valid, the `realm.json` must be under the folder `/opt/keycloak/data/import` in order to be imported at the start time. To accomplish this task, we have developed a new "prefix" action:

`resource_with_destination::<DEST_PATH> | <ORIGIN_PATH>`

For example: `withProperty("KEYCLOAK_IMPORT", "resource_with_destination::/opt/keycloak/data/import | /keycloak-realm.json")`

3. Add container "arguments"(`${ARGS}`) to default `openshift-deployment-template.yml` (required in order to launch keycloak 18.0.0)
4. Add sub-paths to openshiftClient Volumes (required in order to read a configMap from keycloak import command)

### How to use it

Keycloak 18
```
 @KeycloakContainer(command = { "start-dev --import-realm --hostname-strict=false" })
    static KeycloakService keycloak = new KeycloakService("/keycloak-realm.json", "test-realm", "/realms");
```

Note: Previous versions of keycloak as Keycloak 16 or 14 could still use the old way
```
@Container(image = "${keycloak.image}", expectedLog = "Admin console listening", port = KEYCLOAK_PORT)
    static KeycloakService keycloak = new KeycloakService("/keycloak-realm.json", "test-realm");
```

Please check the relevant options

- [X] New feature (non-breaking change which adds functionality)
- [X] Refactoring
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] This change requires a documentation update

### Checklist:
- [X] Example scenarios has been updated / added
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
@pjgg pls share Jenkins jobs links with OpenShift runs in native and JVM mode

**Comment by pjgg** [comment]
I need to review this results: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-jvm-githubci-pablo/1/testReport/

**Review by mjurc — APPROVED** [review]
Thanks for the implemented feature!

LGTM.

**Review by rsvoboda — COMMENTED** [review]
Only one comment to the PR: CustomVolume is in both kube and openshift module

If there are more cases like this in the future, there should be shared module / dependency on kube module

**Pull request merged**
