### PR TITLE
Branching Quarkus version for 1.0.z release

### PR DESCRIPTION
**Pull request by mjurc**
* Bumping Quarkus version to 2.2.5.Final in preparation for Quarkus 2.2
  compatible 1.0.z release branch.

### CODE REVIEW

**Comment by rsvoboda** [comment]
@mjurc you will probably need to pick https://github.com/quarkus-qe/quarkus-test-framework/pull/380

**Comment by mjurc** [comment]
@rsvoboda `1.0.z` branch is for 2.2.z releases - #380 says it is for 2.7 and later. I see a discrepancy :)

**Comment by rsvoboda** [comment]
But we are supposed to use the latest CLI, thus it should get it ++ the change is compatible with 2.6 based cli

**Review by pjgg — APPROVED** [review]
CI checks need to be reviewed

**Review by pjgg — CHANGES_REQUESTED** [review]
Windows Is using "Maven repo" that is not defined

**Review by pjgg — CHANGES_REQUESTED** [review]

**Review by pjgg — APPROVED** [review]

**Comment by pjgg** [comment]
LGTM

**Pull request merged**
