### PR TITLE
Release 1.2.1.Final

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Release for Quarkus 2.13.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
There were three JVM runs today:
https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-jvm-githubci/257 :
- OpenShiftTodoDemoIT: failed in 1 build
- OpenShiftUsingExtensionAndServerlessFunqyKnEventsIT : failed in 1 build

https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-jvm-githubci/256/:
- OpenShiftUsingCustomTemplateResourceIT: failed in 1 build

https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-jvm-githubci/255 :
- OpenShiftUsingExtensionSecurityResourceIT: failed in 1 build
- OpenShiftUsingExtensionAndDockerBuildPingPongResourceIT: failed in 1 build
- OpenShiftUsingExtensionAndServerlessPingPongResourceIT: failed in 1 build
- OpenShiftUsingExtensionPingPongResourceIT: failed in 1 build

Since none of the failures ever repeated, I suggest to ignore them for the purpose of grading of this MR

**Comment by fedinskiy** [comment]
run tests

**Review by mjurc — APPROVED** [review]

**Pull request merged**
