### PR TITLE
Bump Quarkus to 3.2.0.CR1

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Bump Quarkus to 3.2.0.CR1
Remove workaround from https://github.com/quarkus-qe/quarkus-test-framework/pull/814

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
I don't have time to analyze OCP failures ATM, so I won't merge it before I do (or someone else analyze them).

**Comment by michalvavrik** [comment]
Please feel free to remove the label when you analyzed failures, thx.

**Comment by fedinskiy** [comment]
Hmm, there are multiple errors "Connection was closed" which can be reproduced on RHEL, but can not be reproduced on Fedora. Some weird network behavior?

**Comment by fedinskiy** [comment]
@michalvavrik the issue: https://github.com/quarkusio/quarkus/issues/34276

**Comment by michalvavrik** [comment]
Thanks @fedinskiy , in that case we should wait till they fix it. WDYT?

**Pull request closed without merging**
