### PR TITLE
Support FIPS-compatible certificate generation

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Quarkus QE Test Suite HTTP advanced module fails in FIPS-enabled environment as used certs are using unsupported algorithm. This PR unifies and fixes the way we generate these certs. The feature added here remains optional. Existing FW examples test DEV / Prod and also OCP secret mounting.

Please note this needs to be improved in near future to support other scenarios. I'm fixing one thing at the time.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Review by mjurc — APPROVED** [review]
Man, this looks really helpful. Thanks a lot.

**Comment by fedinskiy** [comment]
@michalvavrik it looks like this feature is not documented in our Wiki. Could you add some description there?

**Comment by michalvavrik** [comment]
> @michalvavrik it looks like this feature is not documented in our Wiki. Could you add some description there?

It think Javadoc is sufficient to understand the feature. I'll add some high-level overview to our wiki based on your request, but it won't be anytime soon, I have long backlog.

**Pull request merged**
