### PR TITLE
[fix] Wait for DC ready before scaling

### PR DESCRIPTION
**Pull request by llowinge**
It can happen, that the DC is not ready, in such case is better to wait some time.

### CODE REVIEW

**Comment by llowinge** [comment]
@mjurc Can you look ?

**Review by mjurc — APPROVED** [review]
LGTM, the failure in CLI tests was unreleated, let's wait for the CI for green

**Comment by rsvoboda** [comment]
@llowinge this PR causes troubles in serverless use-case. @mjurc will prepare fix for that.

Looking at the description of this PR I miss more context - what is the problem which the PR fixes / in which cases is not DeploymentConfig available? `It can happen` doesn't feel (to me) like a sufficient explanation

**Comment by llowinge** [comment]
@rsvoboda It happened to me when OpenShift wasn't fast/stable probably and DC wasn't yet created, because after this change i didn't see it again (i mean eg. seeing `Waiting for dc to be ready` multiple times atleast). If it causes troubles you can revert it and if i hit problem in future i will do proper analysis what is wrong. Sorry for inconvenience.

**Comment by rsvoboda** [comment]
The problem is fixed now, Michal did the PR yesterday.

OpenShift wasn't fast/stable ... OCP running in PSI? or local OKD instance?

**Comment by llowinge** [comment]
OCP running in PSI.

**Pull request merged**
