### PR TITLE
[1.3.z] Pinning external application branches to 3.2

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

* Pinning usages of Camel on Quarkus and Quarkus quickstarts to 3.2 release stream branches.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]
Looks good, let's wait for CI.

**Comment by rsvoboda** [comment]
What about `TodoDemoIT`. That should probably have some pinning too @mjurc ?

**Comment by rsvoboda** [comment]
aha, `@Disabled("Disabled until Quarkus 3 is released and TODO application migrates to it")`

**Comment by mjurc** [comment]
Sadly last time that app got an update was with 2.7.1.

**Comment by rsvoboda** [comment]
`Run OpenShift Tests in JVM` are red, @mjurc can you investigate?

**Comment by mjurc** [comment]
@rsvoboda The job needs to be ran on JDK17 executors. I will update it, as JDK11 is deprecated anyway - wdyt?

**Comment by rsvoboda** [comment]
What requires JDK 17?

**Comment by mjurc** [comment]
@rsvoboda The Apache Camel extension for Quarkus quickstart has compilation target set to JDK17. Since we run the tests on JDK 11, the application gets built locally into container image, deployed and referenced from OpenShift deployment.

Sadly, since the executor is on JDK 11, it cannot compile the quickstart:
https://github.com/apache/camel-quarkus-examples/blob/3.2.x/file-bindy-ftp/pom.xml#L41

**Pull request merged**
