### PR TITLE
[1.5.z] Backport/7.10

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

- https://github.com/quarkus-qe/quarkus-test-framework/pull/1279
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1294
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1322
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1330
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1334
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1351
- https://github.com/quarkus-qe/quarkus-test-framework/pull/1346

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backporting
- [ ] Release (follows conventions described in the [RELEASE.md](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md))
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
Backports LGTM. We need CI (including OCP) to confirm.

**Comment by michalvavrik** [comment]
jeez, I forgot I cannot run OCP now :/ ok, let's just use GH CI.

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
All runs are green, including both Jenkins OCP runs, therefore I will merge

**Pull request merged**
